### ISSUE TITLE
Models should connect to the database only when queries are executed

### ISSUE THREAD

**Issue by juliogreff** [spaghettiphp/spaghettiphp#1]
Nowadays, when a model is instantiated, it already connects to the databases, even when it's not needed (i.e. when the model is being used by another actions of the controller but not in the current one). We need to move the connection to another method other than the __construct.

**Comment by juliogreff** [comment]
moved database connection to the first database query. closed by b05cf085a5673fe2c714825a140fe5180e5cbdba

**Comment by juliogreff** [comment]
Reintroduced in a86a6165b36f8785ef90b2938be5df2810bb66f7. Needs fixing

**Comment by djalmaaraujo** [comment]
Can we do something like lazy load in rails?
